description: ''
exclude: ['*.png', img, agent, cert, essay.rst, indexcol.rst, signup.rst, forum.rst,
  help, maintain.rst, demo.rst, about, solutions, projects, common, feedback.rst,
  robots.txt, apps-dev.json, apps.json]
order: [index.rst, tour, apps, cases, purchase, blog]
theme: index.html
theme_base: http://192.168.1.115:6544/themes/everydo/
#theme_base: http://download.zopen.cn/themes/everydo/
title: 易度云办公：企业在线工作平台
